version: '3.8'

services:
  backend:
    build: ./server
    container_name: savr-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./.env
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./client/savr-client
    container_name: savr-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./.env
