version: '3.8'

services:
  backend:
    build: ./server
    container_name: savr-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./.env
    environment:
      - FLASK_ENV=development

  frontend:
    # For development, use a simpler approach that supports hot reloading
    image: node:18
    container_name: savr-frontend
    working_dir: /app
    volumes:
      - ./client/savr-client:/app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
    env_file:
      - ./.env
